let btn1 = parseInt(document.getElementById('btn1').value)
let btn2 = parseInt(document.getElementById('btn2'))
let btn3 = parseInt(document.getElementById('btn3'))
let btnAdd = parseInt(document.getElementById('btn+'))
let btn4 = parseInt(document.getElementById('btn4'))
let btn5 = parseInt(document.getElementById('btn5'))
let btn6 = parseInt(document.getElementById('btn6'))
let btnDel = parseInt(document.getElementById('btn-'))
let btn7 = parseInt(document.getElementById('btn7'))
let btn8 = parseInt(document.getElementById('btn8'))
let btn9 = parseInt(document.getElementById('btn9'))
let btnMul = parseInt(document.getElementById('btn*'))
let btnAC = parseInt(document.getElementById('btnAC'))
let btn0 = parseInt(document.getElementById('btn0'))
let btnResult = parseInt(document.getElementById('btn= '))
let btnDevide = parseInt(document.getElementById('btn/'))
